version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp s3://aws-keys-for-ec2/keystore.p12 ./src/main/resources/
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./target/*.jar
  discard-paths: yes