version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Starting build `date`
  build:
    commands:
      - echo Build started on `date`
      - mvn install

  post_build:
    commands:
      - mv target/*.jar ./
      - echo Build completed on `date`

artifacts:
  files:
    - ./*.jar
#    - .platform/**/*
#  discard-paths: yes
